server:
  port: 9000

security:
  oauth2:
    client:
      client-id: sample-app
      client-secret: 62jxxRnbs7rBwB5F
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token